export const BASE_EDUCATION_ACTION_IDS = [
  "draw.hand",
  "draw.pen",
  "draw.eraser",
  "draw.laser",
  "draw.text",
  "draw.image",
  "draw.clipboard",
  "draw.undo",
  "draw.redo",
  "draw.break.line",
  "draw.break.column",
  "draw.break.page",
  "playback.step.prev",
  "playback.step.next",
  "playback.undo",
  "playback.redo",
  "playback.sound.toggle",
  "canvas.fullscreen.toggle",
  "canvas.sound.toggle",
  "canvas.dock.left",
  "canvas.dock.center",
  "canvas.dock.right",
  "more.file.open",
  "more.file.save",
  "more.local.save",
  "more.local.reset",
  "more.view.reset",
  "more.cursor.toggle",
  "more.layout.canvas-border",
  "more.layout.break-guides",
  "more.overview.toggle",
  "more.overview.ratio.16x9",
  "more.overview.ratio.4x3",
  "more.step.prev",
  "more.step.next",
] as const;

export type BaseEducationActionId = (typeof BASE_EDUCATION_ACTION_IDS)[number];
